apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ifsdoc
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.ifsdoc.replicaCount }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 10 
  template:
    metadata:
      labels:
        app: ifsdoc
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9854'
    spec:
      imagePullSecrets:
      - name: ifsregistersecret
      # imagePullPolicy: Always    # imagePullPolicy should only be changed during developement
      containers:
      - name: ifsdoc
        image: {{ .Values.imageCredentials.registry }}/ifs/ifsapp-doc:latest
        resources:
          limits:
           memory: "5Gi"
           cpu: "2"
           ephemeral-storage: "500M"
          requests:
           memory: "500M"
           cpu: "50m"
           ephemeral-storage: "100M"
        ports:
        - containerPort: 8983
        - containerPort: 9854
        - containerPort: 9100
        env:
        - name: IFSDOC_HOST
          value: {{ .Values.system_url }}
        readinessProbe:
          exec:
            command:
              - bash
              - -c
              - "test -f $PROBES_PATH/status.started"
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ifsdoc
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8983
    name: http
  - port: 9100
    protocol: TCP
    targetPort: 9100
    name: http-nodeexporter
  - port: 9854
    protocol: TCP
    targetPort: 9854
    name: http-admin
  selector:
    app: ifsdoc
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ifsdoc
  namespace: {{ .Values.namespace }}
spec:
  hosts:
  - "ifsdoc"
  http:
  - match:
    - uri:
        prefix: /metrics
    route:
    - destination:
        host: ifsdoc
        port: 
          number: 9854
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: ifsdoc
        port:
          number: 8080
