apiVersion: v1
kind: Service
metadata:
  name: ifsiam
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: http
  selector:
    app: ifsiam
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ifsiam
  namespace: {{ .Values.namespace }}
spec:
  hosts:
  - "ifsiam"
  - "{{ .Values.system_url }}"
  http:
  - match:
    - uri:
        prefix: /auth
    route:
    - destination:
        host: ifsiam
        port:
          number: 8080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ifsiam
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.ifsiam.replicaCount }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 10 
  template:
    metadata:
      labels:
        app: ifsiam
    spec:
      imagePullSecrets:
      - name: ifsregistersecret
      containers:
      - name: ifsiam
        image: {{ .Values.image.repository }}/ifs/ifsiam:{{ .Values.ifsiam.version }}
        resources:
          limits:
           memory: "5G"
           cpu: "2"
          requests:
           memory: "10M"
           cpu: "50m"
        ports:
        - containerPort: 8080
        env:
        - name: KEYCLOAK_USER
          value: keycloak
        - name: KEYCLOAK_PASSWORD
          value: keycloak
        - name: DB_VENDOR
          value: h2
        - name: DB_USER
          value: keycloak
        - name: DB_PASSWORD
          value: password
        - name: JGROUPS_DISCOVERY_PROTOCOL
          value: dns.DNS_PING
        - name: JGROUPS_DISCOVERY_PROPERTIES
          value: dns_query=kube-dns.kube-system.svc.cluster.local
        - name: IFS_REALM_NAME
          value: {{ .Values.namespace }}
        - name: IFS_CLIENT_ID
          value: IFS_bananas
        - name: IFS_NATIVE_CLIENT_ID
          value: IFS_native_bananas
        - name: IFS_CLIENT_SECRET
          value: THIS_IS_A_DUMMY_SECRET
        - name: REDIRECT_URL
          value: http://{{ .Values.system_url }}