apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJybmRkb2NrZXJkZXYuYXp1cmVjci5pbyI6eyJ1c2VybmFtZSI6IjU2Mjk1MTEyLTYyZTgtNGIwNi1hYTYyLTk2YWFiZGNiZTMzZCIsInBhc3N3b3JkIjoickREZVl4NjBzUjdQSVp4amw2c3ZDZUdTZnFLME9xWXBBTmxYME9ZcCtkND0iLCJhdXRoIjoiTlRZeU9UVXhNVEl0TmpKbE9DMDBZakEyTFdGaE5qSXRPVFpoWVdKa1kySmxNek5rT25KRVJHVlplRFl3YzFJM1VFbGFlR3BzTm5OMlEyVkhVMlp4U3pCUGNWbHdRVTVzV0RCUFdYQXJaRFE5In19fQ==
kind: Secret
metadata:
  creationTimestamp: "2019-07-10T03:13:22Z"
  name: ifsregistersecret
  namespace: {{ .Values.namespace }} 
  resourceVersion: "16346779"
  selfLink: /api/v1/namespaces/{{ .Values.namespace }}/secrets/ifsregistersecret
  uid: ace295e0-a2c0-11e9-8d93-8ecae774ee28
type: kubernetes.io/dockerconfigjson
