apiVersion: v1
kind: Secret
metadata:
  name: ifsregistersecret
  namespace: {{ .Values.namespace }}
  selfLink: /api/v1/namespaces/{{ .Values.namespace }}/secrets/ifsregistersecret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}